id = "motoko"
name = "Motoko"
description = "Motoko and Candid support. Visit the repository for more information."
version = "0.0.4"
schema_version = 1
authors = ["Yota Inomoto <yota@perforate.org>"]
repository = "https://github.com/perforate-org/zed-motoko"

[grammars.motoko]
repository = "https://github.com/christoph-dfinity/tree-sitter-motoko"
rev = "891ae5cda01d2e1f1e7fa8155f223bc12f537ead"

[grammars.candid]
repository = "https://github.com/perforate-org/tree-sitter-candid"
rev = "91523a436ae4075e3cb8a341f64c6dd8b8820f25"

[language_servers.motoko-language-server]
name = "Motoko Language Server"
languages = ["Motoko"]
